Calculate mean-interhousehold distance via MST
----------------------------------------------

Load point dataset from csv

```{r load, fig.width=15, fig.height=15, message=F, warning=F}
require(sp)
csv_file <- "data/mmr_hh_spatial.csv"
hh_points <- read.csv(csv_file)

mapping_from <- c("household._gps_longitude", "household._gps_latitude", "Household_geocharacterization.hh_size", "Household_geocharacterization.hh_rooms")
mapping_to <- c("X", "Y", "hh_size", "hh_rooms")
hh_points[,mapping_to] <- hh_points[,mapping_from]
hh_points <- hh_points[,mapping_to]
# transform the points from factors to numerics (NOT VERY INTUITIVE)
hh_points <- transform(hh_points, X=as.numeric(levels(X))[X], Y=as.numeric(levels(Y))[Y])
coordinates(hh_points) <- ~X + Y

# and set the projection
hh_points@proj4string <- CRS("+proj=longlat +datum=WGS84 +ellps=WGS84")

```

Calculate the MST via igraph
```{r create_mst, fig.width=15, fig.height=15, message=F, warning=F}
require(igraph)
require(geosphere)

# create the full graph
edge_df <- data.frame(t(combn(1:nrow(hh_points), 2)))
names(edge_df) <- c("from", "to")

# assign distances
edge_df$weight <- distHaversine(hh_points[edge_df$from,], hh_points[edge_df$to,])
```

